name: Testing stuff

on:
  schedule:
    -cron: '* * * * *'
    

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: https://full-stack-pokedex-app.herokuapp.com
          follow-redirect: no 
          max-attempts: 3 
          retry-delay: 5s 
          retry-all: no 
      
        
        